"""
Hub 页面生成模块

生成 GitHub Pages 首页（报告聚合页），列出所有历史报告，
支持搜索、模式筛选、暗色模式、日期分组。
"""

import json
from collections import defaultdict


def generate_hub_html(manifest: dict) -> str:
    """根据 manifest 生成自包含的 Hub HTML 页面"""
    reports = sorted(
        manifest.get("reports", []),
        key=lambda r: (r.get("date", ""), r.get("time", "")),
        reverse=True,
    )

    # 按日期分组
    grouped: dict[str, list[dict]] = defaultdict(list)
    for r in reports:
        grouped[r.get("date", "unknown")].append(r)

    # 找到每种模式的最新报告
    latest_by_mode: dict[str, dict] = {}
    for r in reports:
        m = r.get("mode", "")
        if m not in latest_by_mode:
            latest_by_mode[m] = r

    manifest_json = json.dumps(manifest, ensure_ascii=False)

    cards_html = _build_cards_html(grouped)
    latest_links_html = _build_latest_links(latest_by_mode)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PulseRadar · The Archive</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Serif+SC:wght@400;600;700&family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&display=swap" rel="stylesheet">
<style>{_HUB_CSS}</style>
</head>
<body data-lang="en">
<div class="container">
  <header class="masthead">
    <div class="masthead-row">
      <div class="masthead-meta-left">
        <div class="masthead-date" id="masthead-date"></div>
        <div class="masthead-issue">
          <span data-i18n-en="THE ARCHIVE" data-i18n-zh="档案目录">THE ARCHIVE</span>
        </div>
      </div>
      <h1 class="masthead-title">PulseRadar</h1>
      <div class="masthead-meta-right">
        <div class="masthead-count">{len(reports)} <span data-i18n-en="ISSUES" data-i18n-zh="期刊">ISSUES</span></div>
        <div class="masthead-tagline" data-i18n-en="ALL EDITIONS" data-i18n-zh="完整收录">ALL EDITIONS</div>
      </div>
    </div>
    <div class="masthead-rule"></div>
    <div class="masthead-controls">
      <button class="ctrl-btn" id="lang-toggle" onclick="toggleLang()" title="Toggle language">中</button>
      <button class="ctrl-btn" onclick="toggleTheme()" title="Toggle theme" id="theme-toggle">◐</button>
    </div>
  </header>

  <div class="toolbar">
    <input type="text" class="search-input" placeholder="Search date or mode" oninput="onSearch(this.value)"
      data-i18n-en-placeholder="Search date or mode" data-i18n-zh-placeholder="搜索日期或模式">
    <div class="mode-filters">
      <button class="mode-btn active" data-mode="all" onclick="filterMode('all')"
        data-i18n-en="All" data-i18n-zh="全部">All</button>
      <button class="mode-btn" data-mode="current" onclick="filterMode('current')"
        data-i18n-en="Current" data-i18n-zh="当前榜单">Current</button>
      <button class="mode-btn" data-mode="daily" onclick="filterMode('daily')"
        data-i18n-en="Daily" data-i18n-zh="全天汇总">Daily</button>
      <button class="mode-btn" data-mode="incremental" onclick="filterMode('incremental')"
        data-i18n-en="Incremental" data-i18n-zh="增量分析">Incremental</button>
    </div>
  </div>

  {latest_links_html}

  <main class="content">
    {cards_html}
  </main>

  <footer class="footer">
    <div class="footer-rule"></div>
    <div class="footer-text">
      <span data-i18n-en="Generated by" data-i18n-zh="由">Generated by</span>
      <span class="project-name">PulseRadar</span>
      <span class="footer-sep">·</span>
      <a href="https://github.com/sansan0/TrendRadar" class="footer-link" target="_blank"
        data-i18n-en="Based on TrendRadar" data-i18n-zh="基于 TrendRadar">Based on TrendRadar</a>
    </div>
  </footer>
</div>
<script>
window.__MANIFEST__ = {manifest_json};
{_HUB_JS}
</script>
</body>
</html>"""


def _build_latest_links(latest_by_mode: dict[str, dict]) -> str:
    if not latest_by_mode:
        return ""
    mode_labels_en = {"current": "Current", "daily": "Daily", "incremental": "Incremental"}
    mode_labels_zh = {"current": "当前榜单", "daily": "全天汇总", "incremental": "增量分析"}
    links = []
    for mode, report in sorted(latest_by_mode.items()):
        label_en = mode_labels_en.get(mode, mode)
        label_zh = mode_labels_zh.get(mode, mode)
        path = report.get("path", "#")
        links.append(
            f'<a href="{path}" class="latest-link" data-i18n-en="{label_en}" data-i18n-zh="{label_zh}">{label_en}</a>'
        )
    return (
        '<div class="latest-bar">'
        '<span class="latest-label" data-i18n-en="LATEST" data-i18n-zh="最新报告">LATEST</span>'
        f'{"".join(links)}'
        "</div>"
    )


_MODE_LABELS_EN = {"current": "Current", "daily": "Daily", "incremental": "Incremental"}
_MODE_LABELS_ZH = {"current": "当前榜单", "daily": "全天汇总", "incremental": "增量分析"}


def _build_cards_html(grouped: dict[str, list[dict]]) -> str:
    sections = []
    for date in sorted(grouped.keys(), reverse=True):
        reports = grouped[date]
        cards = []
        for r in reports:
            mode = r.get("mode", "")
            label_en = _MODE_LABELS_EN.get(mode, r.get("mode_label", mode))
            label_zh = _MODE_LABELS_ZH.get(mode, r.get("mode_label", mode))
            path = r.get("path", "#")
            time_display = r.get("time", "")
            total = r.get("total_titles", 0)
            stats = r.get("stats_count", 0)
            cards.append(
                f'<a href="{path}" class="card" data-mode="{mode}" data-date="{date}">'
                f'<div class="card-time">{time_display}</div>'
                f'<span class="card-badge mode-{mode}" data-i18n-en="{label_en}" data-i18n-zh="{label_zh}">{label_en}</span>'
                f'<div class="card-stats">'
                f'<span class="stat-num">{total}</span>'
                f'<span class="stat-label" data-i18n-en="signals" data-i18n-zh="条新闻">signals</span>'
                f'<span class="stat-sep">·</span>'
                f'<span class="stat-num">{stats}</span>'
                f'<span class="stat-label" data-i18n-en="topics" data-i18n-zh="个关键词">topics</span>'
                f"</div>"
                f"</a>"
            )
        sections.append(
            f'<section class="date-group" data-date="{date}">'
            f'<h2 class="date-heading">{date}</h2>'
            f'<div class="card-grid">{"".join(cards)}</div>'
            f"</section>"
        )
    if not sections:
        return '<p class="empty-state" data-i18n-en="No issues yet" data-i18n-zh="暂无报告">No issues yet</p>'
    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Inline CSS
# ---------------------------------------------------------------------------
_HUB_CSS = """
:root {
  --bg: #fbf9f4;
  --bg-elev: #ffffff;
  --ink: #1a1a1a;
  --ink-soft: #2a2a2a;
  --muted: #6b6b6b;
  --muted-2: #8a8a8a;
  --hairline: #e5e0d8;
  --hairline-strong: #1a1a1a;
  --crimson: #c13a2e;
  --crimson-soft: #e8d5d2;
  --warm: #b3621a;
  --serif: "Playfair Display", "Noto Serif SC", "Source Han Serif SC", "Songti SC", Georgia, serif;
  --serif-cn: "Noto Serif SC", "Source Han Serif SC", "Songti SC", serif;
  --sans: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
}
[data-theme="dark"] {
  --bg: #0b1015;
  --bg-elev: #141a22;
  --ink: #f4ede2;
  --ink-soft: #d8d2c7;
  --muted: #8a8a8a;
  --muted-2: #6f6f6f;
  --hairline: #2a3140;
  --hairline-strong: #f4ede2;
  --crimson: #e85a4d;
  --crimson-soft: #3a1e1c;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body {
  background: var(--bg);
  color: var(--ink);
  font-family: var(--sans);
  -webkit-font-smoothing: antialiased;
  font-size: 14px;
  line-height: 1.5;
}
body[data-lang="zh"] { font-family: var(--serif-cn), var(--sans); }
::selection { background: var(--crimson); color: var(--bg); }
a { color: inherit; text-decoration: none; }
a:hover { color: var(--crimson); }

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px 48px;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

/* ---------- MASTHEAD ---------- */
.masthead { padding-top: 32px; position: relative; }
.masthead-row {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: end;
  gap: 24px;
  padding-bottom: 16px;
}
.masthead-meta-left { text-align: left; font-size: 11px; letter-spacing: 0.18em; color: var(--muted); text-transform: uppercase; }
.masthead-meta-right { text-align: right; font-size: 11px; letter-spacing: 0.18em; color: var(--muted); text-transform: uppercase; }
.masthead-date { font-weight: 600; color: var(--ink-soft); margin-bottom: 4px; }
.masthead-issue { font-weight: 500; }
.masthead-count { font-weight: 700; color: var(--ink-soft); margin-bottom: 4px; font-size: 12px; }
.masthead-tagline { font-weight: 500; }
.masthead-title {
  font-family: var(--serif);
  font-weight: 900;
  font-size: clamp(40px, 6vw, 76px);
  line-height: 0.95;
  letter-spacing: -0.02em;
  text-align: center;
  color: var(--ink);
}
body[data-lang="zh"] .masthead-title { font-family: var(--serif-cn); }
.masthead-rule {
  border-top: 3px double var(--hairline-strong);
  margin-top: 4px;
}
.masthead-controls {
  position: absolute;
  top: 32px;
  right: 0;
  display: flex;
  gap: 6px;
}
.ctrl-btn {
  width: 32px; height: 32px;
  border: 1px solid var(--hairline);
  background: var(--bg-elev);
  color: var(--ink);
  font-family: var(--serif-cn);
  font-size: 14px;
  cursor: pointer;
  border-radius: 0;
  transition: all 0.15s;
  display: inline-flex; align-items: center; justify-content: center;
}
.ctrl-btn:hover { background: var(--ink); color: var(--bg); border-color: var(--ink); }

/* ---------- TOOLBAR ---------- */
.toolbar {
  margin-top: 24px;
  padding: 16px 0;
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  align-items: center;
  border-bottom: 1px solid var(--hairline);
}
.search-input {
  border: none;
  border-bottom: 1px solid var(--hairline);
  background: transparent;
  padding: 6px 4px;
  font-size: 13px;
  font-family: var(--sans);
  color: var(--ink);
  width: 240px;
  outline: none;
  border-radius: 0;
}
.search-input:focus { border-bottom-color: var(--ink); }
.search-input::placeholder { color: var(--muted-2); font-style: italic; }
.mode-filters { display: flex; gap: 0; margin-left: auto; }
.mode-btn {
  border: 1px solid var(--hairline);
  border-right: none;
  background: var(--bg-elev);
  color: var(--ink-soft);
  padding: 6px 14px;
  font-family: var(--sans);
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  cursor: pointer;
  border-radius: 0;
  transition: all 0.15s;
}
.mode-btn:last-child { border-right: 1px solid var(--hairline); }
.mode-btn:hover { background: var(--bg); }
.mode-btn.active { background: var(--ink); color: var(--bg); border-color: var(--ink); }

/* ---------- LATEST BAR ---------- */
.latest-bar {
  margin-top: 16px;
  padding: 12px 0;
  display: flex;
  gap: 16px;
  align-items: center;
  flex-wrap: wrap;
  border-bottom: 1px solid var(--hairline);
}
.latest-label {
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.18em;
  color: var(--crimson);
  text-transform: uppercase;
}
.latest-link {
  font-size: 12px;
  font-weight: 600;
  color: var(--ink);
  padding: 4px 10px;
  border: 1px solid var(--hairline);
  background: var(--bg-elev);
  letter-spacing: 0.04em;
  text-transform: uppercase;
}
.latest-link:hover { background: var(--ink); color: var(--bg); border-color: var(--ink); }

/* ---------- CONTENT ---------- */
.content { padding-top: 32px; flex: 1; }
.date-group { margin-bottom: 40px; }
.date-heading {
  font-family: var(--serif);
  font-size: 20px;
  font-weight: 700;
  color: var(--ink);
  margin-bottom: 16px;
  padding-bottom: 6px;
  border-bottom: 1px solid var(--hairline-strong);
  letter-spacing: -0.01em;
}
body[data-lang="zh"] .date-heading { font-family: var(--serif-cn); }
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1px;
  background: var(--hairline);
  border: 1px solid var(--hairline);
}
.card {
  display: block;
  background: var(--bg-elev);
  padding: 18px 20px;
  text-decoration: none;
  color: inherit;
  transition: background 0.15s;
  position: relative;
}
.card:hover { background: var(--bg); }
.card:hover .card-time { color: var(--crimson); }
.card-time {
  font-family: var(--serif);
  font-size: 28px;
  font-weight: 700;
  color: var(--ink);
  letter-spacing: -0.01em;
  margin-bottom: 8px;
  line-height: 1;
}
.card-badge {
  display: inline-block;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  padding: 2px 8px;
  margin-bottom: 10px;
  border: 1px solid currentColor;
}
.mode-current { color: var(--crimson); }
.mode-daily { color: var(--warm); }
.mode-incremental { color: var(--ink-soft); }
.card-stats {
  font-size: 12px;
  color: var(--muted);
  display: flex;
  gap: 6px;
  align-items: baseline;
  flex-wrap: wrap;
  letter-spacing: 0.02em;
}
.stat-num { font-weight: 700; color: var(--ink-soft); font-size: 13px; }
.stat-label { color: var(--muted); }
.stat-sep { color: var(--muted-2); }

.empty-state {
  text-align: center;
  color: var(--muted);
  padding: 64px 24px;
  font-style: italic;
  font-family: var(--serif);
  font-size: 18px;
}

/* ---------- FOOTER ---------- */
.footer { margin-top: auto; padding-top: 32px; }
.footer-rule { border-top: 1px solid var(--hairline-strong); margin-bottom: 16px; }
.footer-text {
  text-align: center;
  font-size: 11px;
  color: var(--muted);
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.project-name { font-family: var(--serif); font-weight: 700; color: var(--ink); text-transform: none; letter-spacing: 0; }
.footer-sep { margin: 0 8px; color: var(--muted-2); }
.footer-link { color: var(--muted); }
.footer-link:hover { color: var(--crimson); }

/* ---------- RESPONSIVE ---------- */
@media (max-width: 720px) {
  .masthead-row { grid-template-columns: 1fr; gap: 8px; text-align: center; }
  .masthead-meta-left, .masthead-meta-right { text-align: center; }
  .masthead-controls { position: static; justify-content: center; margin-top: 12px; }
  .toolbar { flex-direction: column; align-items: stretch; }
  .search-input { width: 100%; }
  .mode-filters { margin-left: 0; overflow-x: auto; }
  .card-grid { grid-template-columns: 1fr; }
}
"""

# ---------------------------------------------------------------------------
# Inline JS
# ---------------------------------------------------------------------------
_HUB_JS = """
let currentMode = 'all';
let searchTerm = '';
let debounceTimer;

function onSearch(value) {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(function() {
    searchTerm = value.toLowerCase().trim();
    applyFilters();
  }, 200);
}

function filterMode(mode) {
  currentMode = mode;
  document.querySelectorAll('.mode-btn').forEach(function(btn) {
    btn.classList.toggle('active', btn.dataset.mode === mode);
  });
  applyFilters();
}

function applyFilters() {
  document.querySelectorAll('.date-group').forEach(function(group) {
    var cards = group.querySelectorAll('.card');
    var anyVisible = false;
    cards.forEach(function(card) {
      var matchesMode = currentMode === 'all' || card.dataset.mode === currentMode;
      var text = (card.dataset.date + ' ' + card.textContent).toLowerCase();
      var matchesSearch = !searchTerm || text.indexOf(searchTerm) !== -1;
      var visible = matchesMode && matchesSearch;
      card.style.display = visible ? '' : 'none';
      if (visible) anyVisible = true;
    });
    group.style.display = anyVisible ? '' : 'none';
  });
}

function toggleTheme() {
  var body = document.body;
  var next = body.getAttribute('data-theme') === 'dark' ? '' : 'dark';
  body.setAttribute('data-theme', next);
  try { localStorage.setItem('hub-theme', next); } catch(e) {}
}

function applyLang(lang) {
  document.body.dataset.lang = lang;
  document.documentElement.setAttribute('lang', lang === 'zh' ? 'zh-CN' : 'en');
  var btn = document.getElementById('lang-toggle');
  if (btn) btn.textContent = lang === 'zh' ? 'EN' : '中';
  document.querySelectorAll('[data-i18n-en]').forEach(function(el) {
    var v = el.getAttribute(lang === 'zh' ? 'data-i18n-zh' : 'data-i18n-en');
    if (v != null) el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-en-placeholder]').forEach(function(el) {
    var v = el.getAttribute(lang === 'zh' ? 'data-i18n-zh-placeholder' : 'data-i18n-en-placeholder');
    if (v != null) el.placeholder = v;
  });
  try { localStorage.setItem('hub-lang', lang); } catch(e) {}
}
function toggleLang() {
  var current = document.body.dataset.lang === 'zh' ? 'zh' : 'en';
  applyLang(current === 'zh' ? 'en' : 'zh');
}

function setMastheadDate() {
  var el = document.getElementById('masthead-date');
  if (!el) return;
  var reports = (window.__MANIFEST__ && window.__MANIFEST__.reports) || [];
  var latest = reports[0];
  for (var i = 0; i < reports.length; i++) {
    if (!latest || (reports[i].date || '') > (latest.date || '')) latest = reports[i];
  }
  if (latest && latest.date) {
    el.textContent = latest.date;
  } else {
    var d = new Date();
    el.textContent = d.toISOString().slice(0, 10);
  }
}

(function() {
  try {
    var savedTheme = localStorage.getItem('hub-theme');
    if (savedTheme) document.body.setAttribute('data-theme', savedTheme);
  } catch(e) {}
  try {
    var savedLang = localStorage.getItem('hub-lang');
    applyLang(savedLang === 'zh' ? 'zh' : 'en');
  } catch(e) { applyLang('en'); }
  setMastheadDate();
})();
"""
