// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pulseradar/Bold.tsx": () => import("../components/mockups/pulseradar/Bold.tsx"),
  "./components/mockups/pulseradar/Conservative.tsx": () => import("../components/mockups/pulseradar/Conservative.tsx"),
  "./components/mockups/pulseradar/Moderate.tsx": () => import("../components/mockups/pulseradar/Moderate.tsx")
};
